/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

import org.w3c.dom.ls.LSOutput;

import java.util.*;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        LinkedList linkedList = new LinkedList(new Node(1,null));
        linkedList.insert(new Node(2,null));
        linkedList.insert(new Node(3,null));

        linkedList.show();
        if(linkedList.include(linkedList.head, 3)){
            System.out.println(true);
        }else{
            System.out.println(false);
        }
        System.out.println(linkedList);
    }
}
