/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Graph;

import java.util.ArrayList;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


        Graph graph = new Graph();

        graph.addVertex("Bob");
        graph.addVertex("Mary");
        graph.addVertex("Alice");
        graph.addVertex("Carl");

        graph.addEdge("Alice", "Carl");
        graph.addEdge("Bob", "Mary");
        graph.addEdge("Bob", "Alice");

        System.out.println("the graph => " + graph.printGraph());
        System.out.println("the size => " + graph.size());

//        graph.removeEdge("Carl", "Alice");
//        graph.removeVertex("Bob");
//        System.out.println();

//        System.out.println("the graph => " + graph.printGraph());
//        System.out.println("the size => " + graph.size());

        System.out.println();

//        System.out.println(graph.bft());
        System.out.println(graph.dft("Alice"));
        System.out.println(graph.bft("Alice"));

        System.out.println();

        System.out.println(graph.getVertices());

        System.out.println();

        System.out.println(graph.getNeighbors("Bob"));

//        code challege 36

        Graph graph1 = new Graph();

        graph1.addVertex("Pandora");
        graph1.addVertex("Arendelle");
        graph1.addVertex("Metroville");
        graph1.addVertex("Monstroplolis");
        graph1.addVertex("Narnia");
        graph1.addVertex("Naboo");

        graph1.addEdge("Pandora", "Arendelle");
        graph1.addEdge("Arendelle", "Metroville");
        graph1.addEdge("Arendelle", "Monstroplolis");
        graph1.addEdge("Metroville", "Narnia");
        graph1.addEdge("Metroville", "Naboo");
        graph1.addEdge("Metroville", "Monstroplolis");
        graph1.addEdge("Monstroplolis", "Naboo");
        graph1.addEdge("Narnia", "Naboo");

        System.out.println(graph1.bft("Pandora"));


//        code challenge 37
        Graph graph2 = new Graph();

        graph2.addVertex("Pandora");
        graph2.addVertex("Arendelle");
        graph2.addVertex("Metroville");
        graph2.addVertex("Monstroplolis");
        graph2.addVertex("Narnia");
        graph2.addVertex("Naboo");

        graph2.addEdgeWithWeight("Pandora", "Arendelle", 150);
        graph2.addEdgeWithWeight("Arendelle", "Metroville",99);
        graph2.addEdgeWithWeight("Arendelle", "Monstroplolis",42);
        graph2.addEdgeWithWeight("Metroville", "Narnia",37);
        graph2.addEdgeWithWeight("Metroville", "Naboo",26);
        graph2.addEdgeWithWeight("Metroville", "Monstroplolis",105);
        graph2.addEdgeWithWeight("Monstroplolis", "Naboo",73);
        graph2.addEdgeWithWeight("Narnia", "Naboo",250);

        List<String> cities = new ArrayList<>();
        cities.add("Pandora");
        cities.add("Arendelle");
        cities.add("Metroville");

        System.out.println("First Trip ---> "+graph2.businessTrip(graph2,cities));


//        code challenge 38
        Graph graph3 = new Graph();

        graph3.addVertex("Pandora");
        graph3.addVertex("Arendelle");
        graph3.addVertex("Metroville");
        graph3.addVertex("Monstroplolis");
        graph3.addVertex("Narnia");
        graph3.addVertex("Naboo");

        graph3.addEdge("Pandora", "Arendelle");
        graph3.addEdge("Arendelle", "Metroville");
        graph3.addEdge("Arendelle", "Monstroplolis");
        graph3.addEdge("Metroville", "Narnia");
        graph3.addEdge("Metroville", "Naboo");
        graph3.addEdge("Metroville", "Monstroplolis");
        graph3.addEdge("Monstroplolis", "Naboo");
        graph3.addEdge("Narnia", "Naboo");

        System.out.println(graph3.dft("Pandora"));
    }
}

