/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashTable;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        HashTable<String, Integer> studentAllowances = new HashTable<>();
        studentAllowances.add("John", 300);
        studentAllowances.add("Sally", 400);
        studentAllowances.add("Tom", 200);
        studentAllowances.add("Jade", 100);

        System.out.println("The size is => " + studentAllowances.getSize());
        System.out.println("The Sally allowance is => " + studentAllowances.get("Sally"));
        System.out.println("Array cotains Sally =>" + studentAllowances.contains("Sally"));
        System.out.println("Delete Sally => " + studentAllowances.remove("Sally"));
        System.out.println("The size is => " + studentAllowances.getSize());
        System.out.println("Array cotains Sally =>" + studentAllowances.contains("Sally"));
    }
}
