/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashTable;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    public void test(){

        HashTable<String, Integer> clubs = new HashTable<String, Integer>();

        assertTrue(clubs.isEmpty());

    }
    @Test
    public void testAdd() {

        HashTable<String, Integer> resturant = new HashTable<String, Integer>();
        resturant.add("Ward",100);
        assertEquals(1,resturant.getSize());

    }
    @Test
    public void testEmpty() {

        HashTable<String, Integer> resturant = new HashTable<String, Integer>();

        resturant.add("Znbak", 200);
        assertEquals(1,resturant.getSize());
        assertFalse(resturant.isEmpty());
    }
    @Test
    public void testRemove() {

        HashTable<String, Integer> resturant = new HashTable<String, Integer>();
        resturant.add("Znbak", 200);
        assertEquals(1,resturant.getSize());


        resturant.remove("Znbak");
        assertEquals(0,resturant.getSize());
    }

    @Test
    public void testContains() {

        HashTable<String, Integer> resturant = new HashTable<String, Integer>();
        resturant.add("ward",100);
        assertTrue(resturant.contains("ward"));
        assertFalse(resturant.contains("Znbak"));
    }
    }
