/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pseudocode;
//
//import pseudocode.insertionSort.InsertionSort;
//import pseudocode.mergeSort.MergeSort;

import pseudocode.quickSort.QuickSort;

import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

//        int arr[] = {8, 4, 23, 42, 16, 15};
//
//        InsertionSort insertionSort = new InsertionSort();
//       insertionSort.insertionSort(arr);
//
//       for( int arr1 : arr){
//           System.out.println(arr1);
//       }
//        System.out.println(Arrays.toString(arr));

//        int [] mergeArr = {8, 4, 23, 42, 16, 15};
//        MergeSort mergeSort = new MergeSort();
//
//        mergeSort.mergeSort(mergeArr);
//        System.out.println("Merge Array " + Arrays.toString(mergeArr));



//   challenge 28
        int [] sortArr = {8, 4, 23, 42, 16, 15};
        QuickSort quickSort = new QuickSort();

        quickSort.quickSort(sortArr,0, 5);

        System.out.println("SortArray " +Arrays.toString(sortArr));

    }


}
