/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pseudocode;

import pseudocode.insertionSort.InsertionSort;

import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        int arr[] = {8, 4, 23, 42, 16, 15};

        InsertionSort insertionSort = new InsertionSort();
       insertionSort.insertionSort(arr);

       for( int arr1 : arr){
           System.out.println(arr1);
       }
        System.out.println(Arrays.toString(arr));
    }
}
