/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Graph;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test
    public void addVertex(){

        Graph graph = new Graph();

        graph.addVertex("Bob");
        graph.addVertex("Mary");

        assertNotNull(graph.getVertices());
        assertEquals(2,graph.size());
    }

    @Test
    public void addEdge(){

        Graph graph = new Graph();

        graph.addVertex("Bob");
        graph.addVertex("Alice");
        graph.addEdge("Bob", "Alice");

        assertEquals("Vertex{label='Bob'}[Vertex{label='Alice'}]Vertex{label='Alice'}[Vertex{label='Bob'}]", graph.printGraph());
    }

    @Test
    public void vertexNeighbors(){

        Graph graph = new Graph();

        graph.addVertex("Bob");
        graph.addVertex("Alice");
        graph.addVertex("Mary");
        graph.addVertex("Carl")
        ;
        graph.addEdge("Bob", "Mary");
        graph.addEdge("Bob", "Alice");
        graph.addEdge("Mary", "Alice");

        assertEquals("[Vertex{label='Mary'}, Vertex{label='Alice'}]",graph.getNeighbors("Bob").toString());
        assertEquals("[Vertex{label='Bob'}, Vertex{label='Alice'}]", graph.getNeighbors("Mary").toString());

    }


    @Test
    public void emptyGraph(){

        Graph graph = new Graph();
        assertEquals(0,graph.size());
        assertEquals("[]", graph.getVertices().toString());
    }

    @Test
    public void removeVertex(){

        Graph graph = new Graph();

        graph.addVertex("Bob");
        graph.addVertex("Carl");
        graph.addEdge("Bob", "Carl");
        assertEquals("Vertex{label='Bob'}[Vertex{label='Carl'}]Vertex{label='Carl'}[Vertex{label='Bob'}]",graph.printGraph());
        assertEquals(2, graph.size());

        graph.removeVertex("Bob");
        assertEquals("Vertex{label='Carl'}[]",graph.printGraph());
        assertEquals(1, graph.size());
    }

    @Test
    public void removeEdge(){
        Graph graph = new Graph();

        graph.addVertex("Bob");
        graph.addVertex("Carl");
        graph.addEdge("Bob", "Carl");
        assertEquals("Vertex{label='Bob'}[Vertex{label='Carl'}]Vertex{label='Carl'}[Vertex{label='Bob'}]",graph.printGraph());

        graph.removeEdge("Carl", "Bob");
        assertEquals("Vertex{label='Bob'}[]Vertex{label='Carl'}[]", graph.printGraph());
    }
}
